In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/FPDSData.csv")
df = pd.read_csv("../data/FPDSData.csv", low_memory=False)
df

C:\Users\User\AppData\Local\Temp\ipykernel_10288\3848490500.py:1: DtypeWarning: Columns (0: Treasury Account Symbol Sub Account Code, 1: IDV Contracting Agency ID) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/FPDSData.csv")

,Contracting Agency ID,Contracting Agency Name,Contracting Office ID,Contracting Office Name,Country Where Award was Issued,Major Command Name,Modification Number,PIID,Referenced IDV PIID,Referenced IDV Mod Number,...,IDV Referenced IDV PIID,IDV Subcontract Plan,IDV Subcontract Plan Description,IDV Type Of IDC,IDV Type Of IDC Description,IDV Who Can Use,IDV Who Can Use Description,Base and Exercised Options Value,Action Obligation,Base and All Options Value (Total Contract Value)
0,1700,DEPT OF THE NAVY,M67001,COMMANDING GENERAL,USA,USMC,P00001,M6700107P0419,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-540.00,-540.00,-540.00
1,1700,DEPT OF THE NAVY,M67854,COMMANDER,USA,USMC,0,M6785411C8067,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3677241.05,3677241.05,3677241.05
2,1700,DEPT OF THE NAVY,M68909,SUPPLY OFFICER,USA,USMC,0,M6890911M1024,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3960.00,3960.00,3960.00
3,1700,DEPT OF THE NAVY,M68909,SUPPLY OFFICER,USA,USMC,0,M6890911M1026,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13312.00,13312.00,13312.00
4,1700,DEPT OF THE NAVY,N00189,NAVSUP FLT LOG CTR NORFOLK,USA,NAVSUP,P00008,N0018905P0992,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,-9994.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360024,5700,DEPT OF THE AIR FORCE,FA9401,FA9401 377 MSG PK,USA,AFGSC,6,5,FA940114D0004,0,...,NaN,B,PLAN NOT REQUIRED,B,INDEFINITE DELIVERY - INDEFINITE QUANTITY,ONLY MY AGENCY,ONLY THE AGENCY AWARDING THE CONTRACT MAY PLAC...,0.00,0.00,0.00
360025,5700,DEPT OF THE AIR FORCE,FA9401,FA9401 377 MSG PK,USA,AFGSC,P00001,FA940118C0010,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00
360026,5700,DEPT OF THE AIR FORCE,FA9401,FA9401 377 MSG PK,USA,AFGSC,P00001,FA940118C0011,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00
360027,5700,DEPT OF THE AIR FORCE,FA9401,FA9401 377 MSG PK,USA,AFGSC,P00002,FA940117C0010,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00
360028,5700,DEPT OF THE AIR FORCE,FA9401,FA9401 377 MSG PK,USA,AFGSC,P00002,FA940118C0011,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00

In [3]:
df.shape

(360029, 61)

In [4]:
df.head()

,Contracting Agency ID,Contracting Agency Name,Contracting Office ID,Contracting Office Name,Country Where Award was Issued,Major Command Name,Modification Number,PIID,Referenced IDV PIID,Referenced IDV Mod Number,...,IDV Referenced IDV PIID,IDV Subcontract Plan,IDV Subcontract Plan Description,IDV Type Of IDC,IDV Type Of IDC Description,IDV Who Can Use,IDV Who Can Use Description,Base and Exercised Options Value,Action Obligation,Base and All Options Value (Total Contract Value)
0,1700,DEPT OF THE NAVY,M67001,COMMANDING GENERAL,USA,USMC,P00001,M6700107P0419,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-540.00,-540.00,-540.00
1,1700,DEPT OF THE NAVY,M67854,COMMANDER,USA,USMC,0,M6785411C8067,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3677241.05,3677241.05,3677241.05
2,1700,DEPT OF THE NAVY,M68909,SUPPLY OFFICER,USA,USMC,0,M6890911M1024,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3960.00,3960.00,3960.00
3,1700,DEPT OF THE NAVY,M68909,SUPPLY OFFICER,USA,USMC,0,M6890911M1026,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13312.00,13312.00,13312.00
4,1700,DEPT OF THE NAVY,N00189,NAVSUP FLT LOG CTR NORFOLK,USA,NAVSUP,P00008,N0018905P0992,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,-9994.00,0.00

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360029 entries, 0 to 360028
Data columns (total 61 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Contracting Agency ID                              360029 non-null  int64
 1   Contracting Agency Name                            360029 non-null  str
 2   Contracting Office ID                              360029 non-null  str
 3   Contracting Office Name                            360029 non-null  str
 4   Country Where Award was Issued                     360029 non-null  str
 5   Major Command Name                                 359941 non-null  str
 6   Modification Number                                360029 non-null  str
 7   PIID                                               360029 non-null  str
 8   Referenced  IDV PIID                               226071 non-null  str
 9   Referenced IDV Mod Number                          322699 non-null  str
 10  Transaction Number                                 345794 non-null  float64
 11  Date Signed                                        360029 non-null  str
 12  Effective Date                                     360029 non-null  str
 13  Completion Date                                    345794 non-null  str
 14  Est. Ultimate Completion Date                      345794 non-null  str
 15  Fiscal Year                                        360029 non-null  int64
 16  Funding Agency ID                                  360013 non-null  str
 17  Funding Agency Name                                360013 non-null  str
 18  Funding Department ID                              360013 non-null  float64
 19  Funding Department Name                            360013 non-null  str
 20  Funding Office ID                                  360013 non-null  str
 21  Funding Office Name                                359308 non-null  str
 22  (Type of IDC)                                      13379 non-null   str
 23  Multiple or Single Award IDV                       14235 non-null   str
 24  Multiyear Contract Code                            325455 non-null  str
 25  Type of Contract                                   360028 non-null  str
 26  NAICS Code                                         359911 non-null  float64
 27  NAICS Description                                  358714 non-null  str
 28  Principal Place of Performance State Code          275268 non-null  str
 29  Principal Place of Performance City Name           275268 non-null  str
 30  Principal Place of Performance Country Name        345794 non-null  str
 31  Place of Performance Zip Code                      286958 non-null  str
 32  Product or Service Description                     360029 non-null  str
 33  Product or Service Code                            360029 non-null  str
 34  Description of Requirement                         360025 non-null  str
 35  Award or IDV Type                                  360029 non-null  str
 36  Reason For Modification Description                227367 non-null  str
 37  IDV Type                                           226071 non-null  str
 38  Extent Competed                                    359354 non-null  str
 39  Number of Offers Received                          336524 non-null  float64
 40  Treasury Account Symbol Agency Identifier          360029 non-null  int64
 41  Treasury Account Symbol Main Account Code          360029 non-null  int64
 42  Treasury Account Symbol Sub Account Code           15480 non-null   str
 43  IDV NAICS Code                                     226050 non-null  float64
 44  IDV NAICS Description                              225446 non-null  str
 45  IDV Contracting Agency ID                          226071 non-null  str
 46  IDV Contracting Agency Name                        226071 non-null  str
 47  IDV Department ID                                  226071 non-null  float64
 48  IDV Department Name                                226071 non-null  str
 49  IDV Major Program Code                             6750 non-null    str
 50  IDV Referenced IDV Agency Code                     0 non-null       float64
 51  IDV Referenced IDV PIID                            0 non-null       float64
 52  IDV Subcontract Plan                               225753 non-null  str
 53  IDV Subcontract Plan Description                   225753 non-null  str
 54  IDV Type Of IDC                                    214857 non-null  str
 55  IDV Type Of IDC Description                        214857 non-null  str
 56  IDV Who Can Use                                    225162 non-null  str
 57  IDV Who Can Use Description                        216736 non-null  str
 58  Base and Exercised Options Value                   345794 non-null  float64
 59  Action Obligation                                  360029 non-null  float64
 60  Base and All Options Value (Total Contract Value)  360029 non-null  float64
dtypes: float64(11), int64(4), str(46)
memory usage: 373.7 MB

In [6]:
df.describe()

,Contracting Agency ID,Transaction Number,Fiscal Year,Funding Department ID,NAICS Code,Number of Offers Received,Treasury Account Symbol Agency Identifier,Treasury Account Symbol Main Account Code,IDV NAICS Code,IDV Department ID,IDV Referenced IDV Agency Code,IDV Referenced IDV PIID,Base and Exercised Options Value,Action Obligation,Base and All Options Value (Total Contract Value)
count,360029.000000,345794.000000,360029.000000,360013.000000,359911.000000,336524.000000,360029.000000,360029.000000,226050.000000,226071.000000,0.0,0.0,3.457940e+05,3.600290e+05,3.600290e+05
mean,2855.688014,0.073373,2014.567552,9678.641049,266352.452142,5.819939,36.780907,2380.160412,268943.591440,9688.964087,NaN,NaN,2.140429e+06,3.615032e+05,2.603101e+06
std,1585.154451,0.948675,2.549064,366.774893,101833.700198,7.369818,25.328741,744.572506,106096.357583,233.394567,NaN,NaN,8.703254e+08,8.412701e+08,9.652591e+08
min,1700.000000,0.000000,2009.000000,1300.000000,115112.000000,0.000000,9.000000,1106.000000,212312.000000,2800.000000,NaN,NaN,-3.447337e+11,-3.447337e+11,-3.447337e+11
25%,2100.000000,0.000000,2012.000000,9700.000000,236220.000000,1.000000,21.000000,2020.000000,236220.000000,9700.000000,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00
50%,2100.000000,0.000000,2014.000000,9700.000000,236220.000000,4.000000,21.000000,2050.000000,236220.000000,9700.000000,NaN,NaN,1.382400e+04,1.122600e+04,1.165500e+04
75%,2100.000000,0.000000,2017.000000,9700.000000,238190.000000,7.000000,57.000000,3300.000000,238160.000000,9700.000000,NaN,NaN,1.050285e+05,9.700000e+04,1.004579e+05
max,5700.000000,17.000000,2020.000000,9700.000000,928120.000000,152.000000,96.000000,3404.000000,926130.000000,9700.000000,NaN,NaN,3.447339e+11,3.447339e+11,3.447339e+11

In [7]:
df.isnull().sum()

Contracting Agency ID                                     0
Contracting Agency Name                                   0
Contracting Office ID                                     0
Contracting Office Name                                   0
Country Where Award was Issued                            0
                                                      ...
IDV Who Can Use                                      134867
IDV Who Can Use Description                          143293
Base and Exercised Options Value                      14235
Action Obligation                                         0
Base and All Options Value (Total Contract Value)         0
Length: 61, dtype: int64

In [8]:
df.columns.tolist()

['Contracting Agency ID',
 'Contracting Agency Name',
 'Contracting Office ID',
 'Contracting Office Name',
 'Country Where Award was Issued',
 'Major Command Name',
 'Modification Number',
 'PIID',
 'Referenced  IDV PIID',
 'Referenced IDV Mod Number',
 'Transaction Number',
 'Date Signed',
 'Effective Date',
 'Completion Date',
 'Est. Ultimate Completion Date',
 'Fiscal Year',
 'Funding Agency ID',
 'Funding Agency Name',
 'Funding Department ID',
 'Funding Department Name',
 'Funding Office ID',
 'Funding Office Name',
 '(Type of IDC)',
 'Multiple or Single Award IDV',
 'Multiyear Contract Code',
 'Type of Contract',
 'NAICS Code',
 'NAICS Description',
 'Principal Place of Performance State Code',
 'Principal Place of Performance City Name',
 'Principal Place of Performance Country Name',
 'Place of Performance Zip Code',
 'Product or Service Description',
 'Product or Service Code',
 'Description of Requirement',
 'Award or IDV Type',
 'Reason For Modification Description',
 'IDV Type',
 'Extent Competed',
 'Number of Offers Received',
 'Treasury Account Symbol Agency Identifier',
 'Treasury Account Symbol Main Account Code',
 'Treasury Account Symbol Sub Account Code',
 'IDV NAICS Code',
 'IDV NAICS Description',
 'IDV Contracting Agency ID',
 'IDV Contracting Agency Name',
 'IDV Department ID',
 'IDV Department Name',
 'IDV Major Program Code',
 'IDV Referenced IDV Agency Code',
 'IDV Referenced IDV PIID',
 'IDV Subcontract Plan',
 'IDV Subcontract Plan Description',
 'IDV Type Of IDC',
 'IDV Type Of IDC Description',
 'IDV Who Can Use',
 'IDV Who Can Use Description',
 'Base and Exercised Options Value',
 'Action Obligation',
 'Base and All Options Value (Total Contract Value)']

In [9]:
df[
    [
        'Base and Exercised Options Value',
        'Action Obligation',
        'Base and All Options Value (Total Contract Value)'
    ]
].describe()

,Base and Exercised Options Value,Action Obligation,Base and All Options Value (Total Contract Value)
count,3.457940e+05,3.600290e+05,3.600290e+05
mean,2.140429e+06,3.615032e+05,2.603101e+06
std,8.703254e+08,8.412701e+08,9.652591e+08
min,-3.447337e+11,-3.447337e+11,-3.447337e+11
25%,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.382400e+04,1.122600e+04,1.165500e+04
75%,1.050285e+05,9.700000e+04,1.004579e+05
max,3.447339e+11,3.447339e+11,3.447339e+11

In [10]:
df[
    [
        'Base and Exercised Options Value',
        'Action Obligation',
        'Base and All Options Value (Total Contract Value)'
    ]
].isnull().sum()

Base and Exercised Options Value                     14235
Action Obligation                                        0
Base and All Options Value (Total Contract Value)        0
dtype: int64

In [11]:
df[
    [
        'Modification Number',
        'Reason For Modification Description',
        'Type of Contract',
        'Product or Service Description',
        'NAICS Description'
    ]
].head(20)

,Modification Number,Reason For Modification Description,Type of Contract,Product or Service Description,NAICS Description
0,P00001,CLOSE OUT,FIRM FIXED PRICE,CONSTRUCT-RELIGIOUS FACILITIES,MUSICAL GROUPS AND ARTISTS
1,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,COMMERCIAL AND INSTITUTIONAL BUILDING CONSTRUC...
2,0,NaN,FIRM FIXED PRICE,CONSTRUCT-OTHER INDUSTRIAL BLDGS,COMMERCIAL AND INSTITUTIONAL BUILDING CONSTRUC...
3,0,NaN,FIRM FIXED PRICE,CONSTRUCT-TROOP HOUSING,OTHER CONSTRUCTION MATERIAL MERCHANT WHOLESALERS
4,P00008,OTHER ADMINISTRATIVE ACTION,FIRM FIXED PRICE,CONSTRUCT-CONF SPACE & FAC,HOTELS (EXCEPT CASINO HOTELS) AND MOTELS
5,0,NaN,FIRM FIXED PRICE,CONSTRUCT-CONF SPACE & FAC,FURNITURE STORES
6,1,FUNDING ONLY ACTION,FIRM FIXED PRICE,CONSTRUCT-CONF SPACE & FAC,FURNITURE STORES
7,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
8,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
9,0,NaN,FIRM FIXED PRICE,CONSTRUCTION OF AIRPORT RUNWAYS,COMMERCIAL AND INSTITUTIONAL BUILDING CONSTRUC...
10,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,JANITORIAL SERVICES
11,0,NaN,FIRM FIXED PRICE,CONSTRUCTION OF OFFICE BUILDINGS,INDUSTRIAL BUILDING CONSTRUCTION
12,0,NaN,FIRM FIXED PRICE,CONSTRUCT-RECREATIONAL BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
13,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
14,0,NaN,FIRM FIXED PRICE,CONSTRUCTION OF OFFICE BUILDINGS,INDUSTRIAL BUILDING CONSTRUCTION
15,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
16,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION
17,0,NaN,FIRM FIXED PRICE,CONSTRUCT-AMMUNITION FACILITIES,INDUSTRIAL BUILDING CONSTRUCTION
18,0,NaN,FIRM FIXED PRICE,CONSTRUCTION OF OFFICE BUILDINGS,INDUSTRIAL BUILDING CONSTRUCTION
19,0,NaN,FIRM FIXED PRICE,CONSTRUCT-MISC BLDGS,INDUSTRIAL BUILDING CONSTRUCTION

In [12]:
df['PIID'].nunique()

64123

In [13]:
df['Modification Number'].value_counts().head(20)

Modification Number
0         132662
1          39484
P00001     27506
2          19345
P00002     16176
3          10679
P00003     10308
P00004      6907
4           6390
P00005      4864
A00001      4375
5           3976
1A          3608
P00006      3574
A00002      3003
6           2731
P00007      2662
A00003      2277
1B          2251
P00008      2058
Name: count, dtype: int64

In [14]:
df['Type of Contract'].value_counts().head(10)

Type of Contract
FIRM FIXED PRICE                                                                               351366
ORDER DEPENDENT (IDV ALLOWS PRICING ARRANGEMENT TO BE DETERMINED SEPARATELY FOR EACH ORDER)      2034
COST PLUS FIXED FEE                                                                              1400
COST PLUS AWARD FEE                                                                              1387
FIXED PRICE WITH ECONOMIC PRICE ADJUSTMENT                                                       1285
FIXED PRICE                                                                                       976
TIME AND MATERIALS                                                                                493
FIXED PRICE AWARD FEE                                                                             456
COST NO FEE                                                                                       249
FIXED PRICE INCENTIVE                                                                             139
Name: count, dtype: int64

In [15]:
df['Award or IDV Type'].value_counts().head(20)

Award or IDV Type
DELIVERY ORDER         222119
DEFINITIVE CONTRACT    101429
PURCHASE ORDER          18294
IDC                     13560
BPA CALL                 3952
BPA                       482
BOA                       193
Name: count, dtype: int64

In [16]:
df['Product or Service Description'].value_counts().head(20)

Product or Service Description
REPAIR OR ALTERATION OF MISCELLANEOUS BUILDINGS                                  38292
CONSTRUCTION OF MISCELLANEOUS BUILDINGS                                          23411
MAINT-REP-ALT-MISC BLDGS                                                         17098
CONSTRUCT-MISC BLDGS                                                             16857
REPAIR OR ALTERATION OF OFFICE BUILDINGS                                         14188
MAINTENANCE OF OFFICE BUILDINGS                                                  12400
MAINTENANCE OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             10566
CONSTRUCTION OF OFFICE BUILDINGS                                                 10275
REPAIR OR ALTERATION OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                   9699
MAINT- REP-ALTER-ALL OTHER                                                        9243
CONSTRUCTION OF OTHER NON-BUILDING FACILITIES                                     9160
CONSTRUCTION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             9045
MAINTENANCE OF MISCELLANEOUS BUILDINGS                                            8901
REPAIR OR ALTERATION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS     7583
REPAIR OR ALTERATION OF OTHER NON-BUILDING FACILITIES                             7539
CONSTRUCTION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)                  7140
CONSTRUCTION OF HIGHWAYS- ROADS- STREETS- BRIDGES- AND RAILWAYS                   6134
REPAIR OR ALTERATION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)          5333
MAINTENANCE OF OTHER NON-BUILDING FACILITIES                                      5133
MAINTENANCE OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                            4810
Name: count, dtype: int64

In [17]:
sample_piid = df['PIID'].dropna().iloc[0]

sample = df[df['PIID'] == sample_piid][[
    'PIID',
    'Modification Number',
    'Transaction Number',
    'Date Signed',
    'Completion Date',
    'Action Obligation',
    'Base and Exercised Options Value',
    'Base and All Options Value (Total Contract Value)',
    'Reason For Modification Description'
]]

sample

,PIID,Modification Number,Transaction Number,Date Signed,Completion Date,Action Obligation,Base and Exercised Options Value,Base and All Options Value (Total Contract Value),Reason For Modification Description
0,M6700107P0419,P00001,0.0,2011-07-05,2007-09-30,-540.0,-540.0,-540.0,CLOSE OUT

In [18]:
sample_piid = df['PIID'].dropna().iloc[0]

sample = df[df['PIID'] == sample_piid][[
    'PIID',
    'Modification Number',
    'Transaction Number',
    'Date Signed',
    'Completion Date',
    'Action Obligation',
    'Base and Exercised Options Value',
    'Base and All Options Value (Total Contract Value)',
    'Reason For Modification Description'
]]

sample

,PIID,Modification Number,Transaction Number,Date Signed,Completion Date,Action Obligation,Base and Exercised Options Value,Base and All Options Value (Total Contract Value),Reason For Modification Description
0,M6700107P0419,P00001,0.0,2011-07-05,2007-09-30,-540.0,-540.0,-540.0,CLOSE OUT

In [19]:
df['Date Signed'] = pd.to_datetime(df['Date Signed'], errors='coerce')
df['Effective Date'] = pd.to_datetime(df['Effective Date'], errors='coerce')
df['Completion Date'] = pd.to_datetime(df['Completion Date'], errors='coerce')
df['Est. Ultimate Completion Date'] = pd.to_datetime(
    df['Est. Ultimate Completion Date'], errors='coerce'
)

In [20]:
df[['Date Signed', 'Effective Date', 'Completion Date',
    'Est. Ultimate Completion Date']].info()

<class 'pandas.DataFrame'>
RangeIndex: 360029 entries, 0 to 360028
Data columns (total 4 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Date Signed                    360029 non-null  datetime64[us]
 1   Effective Date                 360029 non-null  datetime64[us]
 2   Completion Date                345794 non-null  datetime64[us]
 3   Est. Ultimate Completion Date  345794 non-null  datetime64[us]
dtypes: datetime64[us](4)
memory usage: 11.0 MB

In [21]:
df[['Date Signed', 'Effective Date', 'Completion Date',
    'Est. Ultimate Completion Date']].describe()

,Date Signed,Effective Date,Completion Date,Est. Ultimate Completion Date
count,360029,360029,345794,345794
mean,2014-12-10 04:35:40.187596,2014-11-25 09:45:33.409808,2015-05-03 13:47:59.612717,2015-05-18 16:04:41.008924
min,2008-11-05 00:00:00,2001-02-27 00:00:00,2000-05-02 00:00:00,2000-05-02 00:00:00
25%,2012-09-25 00:00:00,2012-09-20 00:00:00,2013-01-10 00:00:00,2013-01-17 00:00:00
50%,2014-09-26 00:00:00,2014-09-24 00:00:00,2015-02-24 00:00:00,2015-03-05 00:00:00
75%,2016-12-07 00:00:00,2016-11-21 00:00:00,2017-06-05 00:00:00,2017-06-20 00:00:00
max,2020-06-04 00:00:00,3014-09-15 00:00:00,2109-08-31 00:00:00,2109-08-31 00:00:00

In [22]:
df['Product or Service Description'].value_counts().head(30)

Product or Service Description
REPAIR OR ALTERATION OF MISCELLANEOUS BUILDINGS                                  38292
CONSTRUCTION OF MISCELLANEOUS BUILDINGS                                          23411
MAINT-REP-ALT-MISC BLDGS                                                         17098
CONSTRUCT-MISC BLDGS                                                             16857
REPAIR OR ALTERATION OF OFFICE BUILDINGS                                         14188
MAINTENANCE OF OFFICE BUILDINGS                                                  12400
MAINTENANCE OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             10566
CONSTRUCTION OF OFFICE BUILDINGS                                                 10275
REPAIR OR ALTERATION OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                   9699
MAINT- REP-ALTER-ALL OTHER                                                        9243
CONSTRUCTION OF OTHER NON-BUILDING FACILITIES                                     9160
CONSTRUCTION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             9045
MAINTENANCE OF MISCELLANEOUS BUILDINGS                                            8901
REPAIR OR ALTERATION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS     7583
REPAIR OR ALTERATION OF OTHER NON-BUILDING FACILITIES                             7539
CONSTRUCTION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)                  7140
CONSTRUCTION OF HIGHWAYS- ROADS- STREETS- BRIDGES- AND RAILWAYS                   6134
REPAIR OR ALTERATION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)          5333
MAINTENANCE OF OTHER NON-BUILDING FACILITIES                                      5133
MAINTENANCE OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                            4810
MAINT-REP-ALT-OFFICE BLDGS                                                        4712
MAINT-REP-ALT-HWYS-RDS-STS-BRDGS-RA                                               4255
MAINT-REP-ALT-OTHER ADMIN BLDGS                                                   3965
REPAIR OR ALTERATION OF OTHER UTILITIES                                           3506
CONSTRUCT-OTHER ADMIN & SVCS BLDGS                                                3360
REPAIR OR ALTERATION OF OTHER INDUSTRIAL BUILDINGS                                2603
MAINTENANCE OF FAMILY HOUSING FACILITIES                                          2566
CONSTRUCTION OF OTHER AIRFIELD STRUCTURES                                         2365
CONSTRUCTION OF OTHER UTILITIES                                                   2339
CONSTRUCT-TROOP HOUSING                                                           2335
Name: count, dtype: int64

In [23]:
df['Principal Place of Performance Country Name'].value_counts().head(20)

Principal Place of Performance Country Name
UNITED STATES           275322
GERMANY                  17867
AFGHANISTAN              13808
JAPAN                    11031
KOREA- SOUTH              8944
ITALY                     3378
TURKEY                    2124
IRAQ                       989
BAHRAIN                    908
KUWAIT                     855
QATAR                      828
SPAIN                      817
CUBA                       788
DJIBOUTI                   776
HONDURAS                   515
BELGIUM                    496
EGYPT                      464
UNITED ARAB EMIRATES       430
GREECE                     360
PORTUGAL                   355
Name: count, dtype: int64

In [24]:
df['Principal Place of Performance State Code'].value_counts().head(20)

Principal Place of Performance State Code
CA    28567
VA    19996
TX    19374
FL    15904
NC    11738
WA    11113
MD    11088
MO    10093
GA     9159
CO     8667
HI     8645
KY     7847
SC     7718
AK     7166
OK     6332
NY     6292
NJ     5901
AZ     5835
KS     5620
NM     5473
Name: count, dtype: int64

In [25]:
df['Effective Date'].dt.year.value_counts().sort_index().tail(20)

Effective Date
2010     7412
2011    42327
2012    53007
2013    43029
2014    43898
2015    41940
2016    38858
2017    34855
2018    33086
2019    19061
2020       51
2021        1
2022        1
2023        1
2031        1
2061        1
2103        2
2104        1
2105        2
3014        1
Name: count, dtype: int64

In [26]:
df['Completion Date'].dt.year.value_counts().sort_index().tail(20)

Completion Date
2018.0    30332
2019.0    24342
2020.0     7572
2021.0     1662
2022.0     1138
2023.0      446
2024.0      238
2025.0      212
2026.0       18
2027.0        8
2028.0        2
2029.0        8
2030.0        1
2031.0        8
2034.0        1
2035.0       56
2054.0       43
2088.0        1
2107.0        1
2109.0        1
Name: count, dtype: int64

In [27]:
df['Est. Ultimate Completion Date'].dt.year.value_counts().sort_index().tail(20)

Est. Ultimate Completion Date
2021.0    2049
2022.0    1434
2023.0     553
2024.0     310
2025.0     213
2026.0      18
2027.0       8
2028.0       3
2029.0       8
2030.0       2
2031.0       8
2034.0       1
2035.0      56
2053.0      97
2054.0      43
2059.0       1
2088.0       1
2105.0       1
2107.0       3
2109.0       1
Name: count, dtype: int64

In [28]:
df['Product or Service Description'].value_counts().head(30)

Product or Service Description
REPAIR OR ALTERATION OF MISCELLANEOUS BUILDINGS                                  38292
CONSTRUCTION OF MISCELLANEOUS BUILDINGS                                          23411
MAINT-REP-ALT-MISC BLDGS                                                         17098
CONSTRUCT-MISC BLDGS                                                             16857
REPAIR OR ALTERATION OF OFFICE BUILDINGS                                         14188
MAINTENANCE OF OFFICE BUILDINGS                                                  12400
MAINTENANCE OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             10566
CONSTRUCTION OF OFFICE BUILDINGS                                                 10275
REPAIR OR ALTERATION OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                   9699
MAINT- REP-ALTER-ALL OTHER                                                        9243
CONSTRUCTION OF OTHER NON-BUILDING FACILITIES                                     9160
CONSTRUCTION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS             9045
MAINTENANCE OF MISCELLANEOUS BUILDINGS                                            8901
REPAIR OR ALTERATION OF OTHER ADMINISTRATIVE FACILITIES AND SERVICE BUILDINGS     7583
REPAIR OR ALTERATION OF OTHER NON-BUILDING FACILITIES                             7539
CONSTRUCTION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)                  7140
CONSTRUCTION OF HIGHWAYS- ROADS- STREETS- BRIDGES- AND RAILWAYS                   6134
REPAIR OR ALTERATION OF RESTORATION OF REAL PROPERTY (PUBLIC OR PRIVATE)          5333
MAINTENANCE OF OTHER NON-BUILDING FACILITIES                                      5133
MAINTENANCE OF HIGHWAYS-ROADS-STREETS-BRIDGES-RAILWAYS                            4810
MAINT-REP-ALT-OFFICE BLDGS                                                        4712
MAINT-REP-ALT-HWYS-RDS-STS-BRDGS-RA                                               4255
MAINT-REP-ALT-OTHER ADMIN BLDGS                                                   3965
REPAIR OR ALTERATION OF OTHER UTILITIES                                           3506
CONSTRUCT-OTHER ADMIN & SVCS BLDGS                                                3360
REPAIR OR ALTERATION OF OTHER INDUSTRIAL BUILDINGS                                2603
MAINTENANCE OF FAMILY HOUSING FACILITIES                                          2566
CONSTRUCTION OF OTHER AIRFIELD STRUCTURES                                         2365
CONSTRUCTION OF OTHER UTILITIES                                                   2339
CONSTRUCT-TROOP HOUSING                                                           2335
Name: count, dtype: int64

In [29]:
df['Principal Place of Performance Country Name'].value_counts().head(20)

Principal Place of Performance Country Name
UNITED STATES           275322
GERMANY                  17867
AFGHANISTAN              13808
JAPAN                    11031
KOREA- SOUTH              8944
ITALY                     3378
TURKEY                    2124
IRAQ                       989
BAHRAIN                    908
KUWAIT                     855
QATAR                      828
SPAIN                      817
CUBA                       788
DJIBOUTI                   776
HONDURAS                   515
BELGIUM                    496
EGYPT                      464
UNITED ARAB EMIRATES       430
GREECE                     360
PORTUGAL                   355
Name: count, dtype: int64

In [30]:
df.groupby('Modification Number')['Action Obligation'].agg(
    ['count', 'sum', 'mean']
).head(20)

                      count           sum           mean
Modification Number
0                    132662  1.072520e+11  808460.661309
0A                        3  9.496000e+03    3165.333333
0B                        1  0.000000e+00       0.000000
0C                        1  3.340600e+04   33406.000000
0E                        1  0.000000e+00       0.000000
0F                        1 -4.100000e+02    -410.000000
0G                        1  5.436600e+04   54366.000000
0H                        1  2.843780e+05  284378.000000
0J                        1  7.200000e+04   72000.000000
0K                        1  6.498100e+04   64981.000000
1                     39484 -9.992566e+08  -25307.887038
10                      862  1.071156e+08  124264.004455
11                      708  8.594966e+07  121397.826568
12                      576  9.912452e+07  172091.174670
13                      455  3.587616e+07   78848.697121
14                      377  2.814553e+07   74656.587454
15                      323  6.129297e+07  189761.503003
16                      272  2.664586e+07   97962.709081
17                      246  1.812690e+07   73686.592561
18                      220  1.977062e+07   89866.434591

In [31]:
df.groupby('Modification Number')[
    'Base and All Options Value (Total Contract Value)'
].agg(
    ['count', 'mean', 'min', 'max']
).head(20)

                      count          mean           min           max
Modification Number
0                    132662  7.709531e+06  0.000000e+00  6.000000e+10
0A                        3  3.165333e+03  0.000000e+00  9.496000e+03
0B                        1  0.000000e+00  0.000000e+00  0.000000e+00
0C                        1  3.340600e+04  3.340600e+04  3.340600e+04
0E                        1  0.000000e+00  0.000000e+00  0.000000e+00
0F                        1 -4.100000e+02 -4.100000e+02 -4.100000e+02
0G                        1  5.436600e+04  5.436600e+04  5.436600e+04
0H                        1  2.843780e+05  2.843780e+05  2.843780e+05
0J                        1  7.200000e+04  7.200000e+04  7.200000e+04
0K                        1  6.498100e+04  6.498100e+04  6.498100e+04
1                     39484  4.645689e+05 -1.980810e+09  3.172976e+09
10                      862  1.215503e+05 -1.714582e+07  1.320944e+07
11                      708 -1.133892e+05 -3.036405e+08  7.410892e+07
12                      576  2.750497e+05 -3.127344e+06  5.357908e+07
13                      455  3.341744e+05 -2.530759e+06  1.049210e+08
14                      377  1.991469e+05 -3.924234e+06  2.239064e+07
15                      323  2.641083e+05 -4.491116e+06  1.900000e+07
16                      272  2.127576e+05 -6.378618e+06  3.098056e+07
17                      246  7.344026e+04 -2.291769e+06  3.420705e+06
18                      220  3.661078e+05 -4.726878e+06  6.953992e+07

In [32]:
df[['Action Obligation',
    'Base and Exercised Options Value',
    'Base and All Options Value (Total Contract Value)']].corr()

,Action Obligation,Base and Exercised Options Value,Base and All Options Value (Total Contract Value)
Action Obligation,1.000000,0.986318,0.871555
Base and Exercised Options Value,0.986318,1.000000,0.999999
Base and All Options Value (Total Contract Value),0.871555,0.999999,1.000000